version: '2'
services:
  fab05:
    image: openswitch/local_build
    container_name: "fab05"
    privileged: true
    ports:
      - "11022:22"
      - "11443:443"
    volumes:
      - /tmp:/tmp
      - /dev/log:/dev/log
      - /sys/fs/cgroup:/sys/fs/cgroup
    networks:
      - default
    command: /sbin/init
  fab06:
    image: openswitch/local_build
    container_name: "fab06"
    privileged: true
    ports:
      - "12022:22"
      - "12443:443"
    volumes:
      - /tmp:/tmp
      - /dev/log:/dev/log
      - /sys/fs/cgroup:/sys/fs/cgroup
    networks:
      - default
    command: /sbin/init
  fab07:
    image: openswitch/local_build
    container_name: "fab07"
    privileged: true
    ports:
      - "13022:22"
      - "13443:443"
    volumes:
      - /tmp:/tmp
      - /dev/log:/dev/log
      - /sys/fs/cgroup:/sys/fs/cgroup
    networks:
      - default
    command: /sbin/init
  fab08:
    image: openswitch/local_build
    container_name: "fab08"
    privileged: true
    ports:
      - "14022:22"
      - "14443:443"
    volumes:
      - /tmp:/tmp
      - /dev/log:/dev/log
      - /sys/fs/cgroup:/sys/fs/cgroup
    networks:
      - default
    command: /sbin/init
  csw01:
    image: openswitch/local_build
    container_name: "csw01"
    privileged: true
    ports:
      - "21022:22"
      - "21443:443"
    volumes:
      - /tmp:/tmp
      - /dev/log:/dev/log
      - /sys/fs/cgroup:/sys/fs/cgroup
    networks:
      - default
    command: /sbin/init
  csw02:
    image: openswitch/local_build
    container_name: "csw02"
    privileged: true
    ports:
      - "22022:22"
      - "22443:443"
    volumes:
      - /tmp:/tmp
      - /dev/log:/dev/log
      - /sys/fs/cgroup:/sys/fs/cgroup
    networks:
      - default
    command: /sbin/init
  csw03:
    image: openswitch/local_build
    container_name: "csw03"
    privileged: true
    ports:
      - "23022:22"
      - "23443:443"
    volumes:
      - /tmp:/tmp
      - /dev/log:/dev/log
      - /sys/fs/cgroup:/sys/fs/cgroup
    networks:
      - default
    command: /sbin/init
  csw04:
    image: openswitch/local_build
    container_name: "csw04"
    privileged: true
    ports:
      - "24022:22"
      - "24443:443"
    volumes:
      - /tmp:/tmp
      - /dev/log:/dev/log
      - /sys/fs/cgroup:/sys/fs/cgroup
    networks:
      - default
    command: /sbin/init
  csw05:
    image: openswitch/local_build
    container_name: "csw05"
    privileged: true
    ports:
      - "25022:22"
      - "25443:443"
    volumes:
      - /tmp:/tmp
      - /dev/log:/dev/log
      - /sys/fs/cgroup:/sys/fs/cgroup
    networks:
      - default
    command: /sbin/init
  csw06:
    image: openswitch/local_build
    container_name: "csw06"
    privileged: true
    ports:
      - "26022:22"
      - "26443:443"
    volumes:
      - /tmp:/tmp
      - /dev/log:/dev/log
      - /sys/fs/cgroup:/sys/fs/cgroup
    networks:
      - default
    command: /sbin/init
  csw07:
    image: openswitch/local_build
    container_name: "csw07"
    privileged: true
    ports:
      - "27022:22"
      - "27443:443"
    volumes:
      - /tmp:/tmp
      - /dev/log:/dev/log
      - /sys/fs/cgroup:/sys/fs/cgroup
    networks:
      - default
    command: /sbin/init
  csw08:
    image: openswitch/local_build
    container_name: "csw08"
    privileged: true
    ports:
      - "28022:22"
      - "28443:443"
    volumes:
      - /tmp:/tmp
      - /dev/log:/dev/log
      - /sys/fs/cgroup:/sys/fs/cgroup
    networks:
      - default
    command: /sbin/init
  asw01:
    image: openswitch/local_build
    container_name: "asw01"
    privileged: true
    ports:
      - "31022:22"
      - "31443:443"
    volumes:
      - /tmp:/tmp
      - /dev/log:/dev/log
      - /sys/fs/cgroup:/sys/fs/cgroup
    networks:
      - default
    command: /sbin/init
  asw02:
    image: openswitch/local_build
    container_name: "asw02"
    privileged: true
    ports:
      - "32022:22"
      - "32443:443"
    volumes:
      - /tmp:/tmp
      - /dev/log:/dev/log
      - /sys/fs/cgroup:/sys/fs/cgroup
    networks:
      - default
    command: /sbin/init
  asw03:
    image: openswitch/local_build
    container_name: "asw03"
    privileged: true
    ports:
      - "33022:22"
      - "33443:443"
    volumes:
      - /tmp:/tmp
      - /dev/log:/dev/log
      - /sys/fs/cgroup:/sys/fs/cgroup
    networks:
      - default
    command: /sbin/init
  asw04:
    image: openswitch/local_build
    container_name: "asw04"
    privileged: true
    ports:
      - "34022:22"
      - "34443:443"
    volumes:
      - /tmp:/tmp
      - /dev/log:/dev/log
      - /sys/fs/cgroup:/sys/fs/cgroup
    networks:
      - default
    command: /sbin/init
  host1:
    image: server/local_build
    container_name: "host1"
    privileged: true
    ports:
      - "41022:22"
    networks:
      - default
    command: /usr/sbin/sshd -D
  host2:
    image: server/local_build
    container_name: "host2"
    privileged: true
    ports:
      - "42022:22"
    networks:
      - default
    command: /usr/sbin/sshd -D
