---
- name: teardown docker containers
  hosts: docker
  gather_facts: no
  tasks:
    - name: shutdown fab containers
      command: docker-compose -f docker-compose-fab.yaml down --remove-orphans
    - name: shutdown csw containers
      command: docker-compose -f docker-compose-csw.yaml down --remove-orphans
    - name: shutdown asw containers
      command: docker-compose -f docker-compose-asw.yaml down --remove-orphans
    - pause: seconds=5
    - name: removing the network temp file
      sudo: yes
      file: path="{{ docker_network_done_file }}" state=absent
#    - name: removing the network host temp file
#      sudo: yes
#      file: path="{{ docker_network_done_file_host }}" state=absent
    - name: removing all the files copied to the docker host
      file: path={{ item }} state=absent
      with_items:
        - docker-compose.yaml
        - Dockerfile
        - ops-if-netns.sh
        - "{{ your_public_key }}"
        - server/Dockerfile
        - server
