---
ops_vrfs:
  - name: vrf_default
    ports: [1, 2, 3, 4, 5]
    bgp_routers:
      - as_number: 64901
        router_id: 10.0.8.3
        networks: [10.0.8.2/31, 10.0.9.2/31, 10.0.10.2/31,  10.0.11.2/31, 10.0.54.0/24]
        neighbors:
          - address: 10.0.8.2
            remote_as: 64851
          - address: 10.0.9.2
            remote_as: 64851
          - address: 10.0.10.2
            remote_as: 64851
          - address: 10.0.11.2
            remote_as: 64851
          - address: 10.0.54.2
            remote_as: 64904

ops_ports:
  - name: 2
    ipv4_address: 10.0.8.3/31
  - name: 3
    ipv4_address: 10.0.9.3/31
  - name: 4
    ipv4_address: 10.0.10.3/31
  - name: 5
    ipv4_address: 10.0.11.3/31
  - name: 1
    ipv4_address: 10.0.54.1/24
