---
ops_vrfs:
  - name: vrf_default
    ports: [1, 2, 3, 4, 5]
    bgp_routers:
      - as_number: 64900
        router_id: 10.0.8.1
        networks: [10.0.8.0/31, 10.0.9.0/31, 10.0.10.0/31,  10.0.11.0/31, 10.0.53.0/24]
        neighbors:
          - address: 10.0.8.0
            remote_as: 64851
          - address: 10.0.9.0
            remote_as: 64851
          - address: 10.0.10.0
            remote_as: 64851
          - address: 10.0.11.0
            remote_as: 64851
          - address: 10.0.53.2
            remote_as: 64904

ops_ports:
  - name: 2
    ipv4_address: 10.0.8.1/31
  - name: 3
    ipv4_address: 10.0.9.1/31
  - name: 4
    ipv4_address: 10.0.10.1/31
  - name: 5
    ipv4_address: 10.0.11.1/31
  - name: 1
    ipv4_address: 10.0.53.1/24
