---
ops_vrfs:
  - name: vrf_default
    ports: [1, 2, 3, 4, 5, 6]
    bgp_routers:
      - as_number: 64850
        router_id: 10.0.20.1
        networks: [10.0.20.0/31, 10.0.20.32/31, 10.0.20.64/31, 10.0.20.96/31, 10.0.4.0/31, 10.0.4.2/31]
        neighbors:
          - address: 10.0.20.0
            remote_as: 64700
          - address: 10.0.20.32
            remote_as: 64700
          - address: 10.0.20.64
            remote_as: 64700
          - address: 10.0.20.96
            remote_as: 64700
          - address: 10.0.4.1
            remote_as: 64900
          - address: 10.0.4.3
            remote_as: 64901

ops_ports:
  - name: 1
    ipv4_address: 10.0.20.1/31
  - name: 2
    ipv4_address: 10.0.20.33/31
  - name: 3
    ipv4_address: 10.0.20.65/31
  - name: 4
    ipv4_address: 10.0.20.97/31
  - name: 5
    ipv4_address: 10.0.4.0/31
  - name: 6
    ipv4_address: 10.0.4.2/31
