---
ops_vrfs:
  - name: vrf_default
    ports: [1, 2, 3, 4, 5, 6]
    bgp_routers:
      - as_number: 64851
        router_id: 10.0.20.11
        networks: [10.0.20.10/31, 10.0.20.42/31, 10.0.20.74/31, 10.0.20.106/31, 10.0.9.0/31, 10.0.9.2/31]
        neighbors:
          - address: 10.0.20.10
            remote_as: 64700
          - address: 10.0.20.42
            remote_as: 64700
          - address: 10.0.20.74
            remote_as: 64700
          - address: 10.0.20.106
            remote_as: 64700
          - address: 10.0.9.1
            remote_as: 64900
          - address: 10.0.9.3
            remote_as: 64901

ops_ports:
  - name: 1
    ipv4_address: 10.0.20.11/31
  - name: 2
    ipv4_address: 10.0.20.43/31
  - name: 3
    ipv4_address: 10.0.20.75/31
  - name: 4
    ipv4_address: 10.0.20.107/31
  - name: 5
    ipv4_address: 10.0.9.0/31
  - name: 6
    ipv4_address: 10.0.9.2/31
