---
ops_vrfs:
  - name: vrf_default
    ports: [1, 2, 3, 4, 5, 6]
    bgp_routers:
      - as_number: 64851
        router_id: 10.0.20.13
        networks: [10.0.20.12/31, 10.0.20.44/31, 10.0.20.76/31, 10.0.20.108/31, 10.0.10.0/31, 10.0.10.2/31]
        neighbors:
          - address: 10.0.20.12
            remote_as: 64700
          - address: 10.0.20.44
            remote_as: 64700
          - address: 10.0.20.76
            remote_as: 64700
          - address: 10.0.20.108
            remote_as: 64700
          - address: 10.0.10.1
            remote_as: 64900
          - address: 10.0.10.3
            remote_as: 64901

ops_ports:
  - name: 1
    ipv4_address: 10.0.20.13/31
  - name: 2
    ipv4_address: 10.0.20.45/31
  - name: 3
    ipv4_address: 10.0.20.77/31
  - name: 4
    ipv4_address: 10.0.20.109/31
  - name: 5
    ipv4_address: 10.0.10.0/31
  - name: 6
    ipv4_address: 10.0.10.2/31
