---
ops_vrfs:
  - name: vrf_default
    ports: [1, 2, 3, 4, 5, 6]
    bgp_routers:
      - as_number: 64850
        router_id: 10.0.20.5
        networks: [10.0.20.4/31, 10.0.20.36/31, 10.0.20.68/31, 10.0.20.100/31, 10.0.6.0/31, 10.0.6.2/31]
        neighbors:
          - address: 10.0.20.4
            remote_as: 64700
          - address: 10.0.20.36
            remote_as: 64700
          - address: 10.0.20.68
            remote_as: 64700
          - address: 10.0.20.100
            remote_as: 64700
          - address: 10.0.6.1
            remote_as: 64900
          - address: 10.0.6.3
            remote_as: 64901

ops_ports:
  - name: 1
    ipv4_address: 10.0.20.5/31
  - name: 2
    ipv4_address: 10.0.20.37/31
  - name: 3
    ipv4_address: 10.0.20.69/31
  - name: 4
    ipv4_address: 10.0.20.101/31
  - name: 5
    ipv4_address: 10.0.6.0/31
  - name: 6
    ipv4_address: 10.0.6.2/31
