---
ops_vrfs:
  - name: vrf_default
    ports: [1, 2, 3, 4, 5, 6]
    bgp_routers:
      - as_number: 64851
        router_id: 10.0.20.9
        networks: [10.0.20.8/31, 10.0.20.40/31, 10.0.20.72/31, 10.0.20.104/31, 10.0.8.0/31, 10.0.8.2/31]
        neighbors:
          - address: 10.0.20.8
            remote_as: 64700
          - address: 10.0.20.40
            remote_as: 64700
          - address: 10.0.20.72
            remote_as: 64700
          - address: 10.0.20.104
            remote_as: 64700
          - address: 10.0.8.1
            remote_as: 64900
          - address: 10.0.8.3
            remote_as: 64901

ops_ports:
  - name: 1
    ipv4_address: 10.0.20.9/31
  - name: 2
    ipv4_address: 10.0.20.41/31
  - name: 3
    ipv4_address: 10.0.20.73/31
  - name: 4
    ipv4_address: 10.0.20.105/31
  - name: 5
    ipv4_address: 10.0.8.0/31
  - name: 6
    ipv4_address: 10.0.8.2/31
