---
ops_vrfs:
  - name: vrf_default
    ports: [1, 2, 3, 4, 5, 6, 7, 8, 9]
    bgp_routers:
      - as_number: 64700
        router_id: 10.0.20.32
        networks: [10.0.20.32/31, 10.0.20.34/31, 10.0.20.36/31, 10.0.20.38/31, 10.0.20.40/31, 10.0.20.42/31, 10.0.20.44/31, 10.0.20.46/31, 10.0.42.0/24]
        neighbors:
          - address: 10.0.20.33
            remote_as: 64850
          - address: 10.0.20.35
            remote_as: 64850
          - address: 10.0.20.37
            remote_as: 64850
          - address: 10.0.20.39
            remote_as: 64850
          - address: 10.0.20.41
            remote_as: 64851
          - address: 10.0.20.43
            remote_as: 64851
          - address: 10.0.20.45
            remote_as: 64851
          - address: 10.0.20.47
            remote_as: 64851
ops_ports:
  - name: 2
    ipv4_address: 10.0.20.32/31
  - name: 3
    ipv4_address: 10.0.20.34/31
  - name: 4
    ipv4_address: 10.0.20.36/31
  - name: 5
    ipv4_address: 10.0.20.38/31
  - name: 6
    ipv4_address: 10.0.20.40/31
  - name: 7
    ipv4_address: 10.0.20.42/31
  - name: 8
    ipv4_address: 10.0.20.44/31
  - name: 9
    ipv4_address: 10.0.20.46/31
  - name: 1
    ipv4_address: 10.0.42.1/24
