---
ops_vrfs:
  - name: vrf_default
    ports: [1, 2, 3, 4, 5, 6, 7, 8, 9]
    bgp_routers:
      - as_number: 64700
        router_id: 10.0.20.0
        networks: [10.0.20.0/31, 10.0.20.2/31, 10.0.20.4/31, 10.0.20.6/31, 10.0.20.8/31, 10.0.20.10/31, 10.0.20.12/31, 10.0.20.14/31, 10.0.41.0/24]
        neighbors:
          - address: 10.0.20.1
            remote_as: 64850
          - address: 10.0.20.3
            remote_as: 64850
          - address: 10.0.20.5
            remote_as: 64850
          - address: 10.0.20.7
            remote_as: 64850
          - address: 10.0.20.9
            remote_as: 64851
          - address: 10.0.20.11
            remote_as: 64851
          - address: 10.0.20.13
            remote_as: 64851
          - address: 10.0.20.15
            remote_as: 64851
ops_ports:
  - name: 2
    ipv4_address: 10.0.20.0/31
  - name: 3
    ipv4_address: 10.0.20.2/31
  - name: 4
    ipv4_address: 10.0.20.4/31
  - name: 5
    ipv4_address: 10.0.20.6/31
  - name: 6
    ipv4_address: 10.0.20.8/31
  - name: 7
    ipv4_address: 10.0.20.10/31
  - name: 8
    ipv4_address: 10.0.20.12/31
  - name: 9
    ipv4_address: 10.0.20.14/31
  - name: 1
    ipv4_address: 10.0.41.1/24
